services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: kea
      MYSQL_DATABASE: kea
      MYSQL_USER: kea
      MYSQL_PASSWORD: kea
      MYSQL_HOST: db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # todo:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     MYSQL_DATABASE: kea
  #     MYSQL_USER: kea
  #     MYSQL_PASSWORD: kea
  #     MYSQL_HOST: db

volumes:
  db_data:
